name: quiz-response-pdfs
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python=3.7
  - python-dotenv
  - reportlab
  - termcolor
  - requests
  - jupyter
  - pandas
  - pip
  - pip:
      - canvasapi==2.0.0
