name: quiz-response-pdfs
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python>=3.7.0
  - python-dotenv
  - reportlab
  - termcolor
  - requests
  - jupyter
  - pandas
  - pip
  - pip:
      - canvasapi>=2.0.0
